name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Extract version from composer.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' composer.json)
          echo "::set-output name=VERSION::$VERSION"

      - name: Build and push Laravel App image with latest tag
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t alpakagb/laravelapp:latest -f Dockerfile.prod .
          docker push alpakagb/laravelapp:latest

      - name: Build and push Laravel App image with version tag
        env:
          DOCKER_BUILDKIT: 1
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          docker build -t alpakagb/laravelapp:$VERSION -f Dockerfile .
          docker push alpakagb/laravelapp:$VERSION
