name: Laravel Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Update/Upgrade
        run: |
          sudo apt-get update
          sudo apt-get install -y
          sudo apt-get upgrade -y

      - name: Copy environment files
        run: |
          sudo chown -R www-data:www-data .
          sudo chmod -R 777 .
          sudo chmod -R 777 storage bootstrap/cache
          cp .env.example .env
          cp nginx/conf.d/laravel.conf.example nginx/conf.d/laravel.conf
          cp nginx/conf.d/laravel.conf.example nginx/conf.d/default.conf

      - name: Install PHP dependencies
        run: |
          sudo curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer --version
          sudo curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
          sudo apt-get install -y nodejs
          npm --version
          sudo apt-get install -y netcat-openbsd
          composer install --no-interaction --no-plugins --no-scripts
          npm install
          php artisan key:generate
          php artisan config:cache
          sudo chown -R www-data:www-data .
          sudo chmod -R 777 .
          sudo chmod -R 777 storage bootstrap/cache

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          docker ps

      - name: Check Docker services status
        run: |
          docker-compose ps
          docker-compose logs app
          docker-compose logs webserver
          docker-compose logs db
          docker-compose logs phpmyadmin

      - name: Debug Docker setup
        run: |
          docker-compose exec app ls -la
          docker-compose exec app ls -la storage
          docker-compose exec app ls -la bootstrap/cache
          docker-compose exec app cat .env
          docker-compose exec app cat nginx/conf.d/laravel.conf

      - name: Run tests inside Docker container
        run: |
          sleep 40
          docker-compose exec app php artisan test

      - name: Collect logs
        if: failure()
        run: |
          docker-compose logs app
          docker-compose logs webserver
          docker-compose logs db
          docker-compose logs phpmyadmin
