name: Laravel Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install PHP dependencies
        run: |
          cp .env.example .env
          cp nginx/conf.d/laravel.conf.example nginx/conf.d/laravel.conf
          pwd
          ls -l
          ls -a
          ls -a ./nginx/conf.d
          sleep 40
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
          php artisan key:generate
          php artisan config:cache

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for application to be ready
        run: |
          timeout=300 # Timeout after 5 minutes
          until curl -sSf http://localhost:8081; do
            timeout=$(($timeout - 1))
            if [ $timeout -eq 0 ]; then
              echo "Application not ready within timeout."
              exit 1
            fi
            echo "Waiting for application to be ready..."
            sleep 40
          done

      - name: Run tests inside Docker container
        run: docker-compose exec -T app php artisan test
