name: Laravel Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3307:3306
          - 8081:80
          - 8082:80
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy environment files
        run: |
          cp .env.example .env
          cp nginx/conf.d/laravel.conf.example nginx/conf.d/laravel.conf

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps
          sleep 40

      - name: Wait for services to be ready
        run: |
          docker-compose run --rm app sh -c "until nc -z -v -w30 db 3306; do echo 'Waiting for database connection...'; sleep 1; done"

      - name: Run Laravel tests
        run: docker-compose run --rm app php artisan test

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down -v
