name: Laravel Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install PHP dependencies
        run: |
          cp .env.example .env
          cp nginx/conf.d/laravel.conf.example nginx/conf.d/laravel.conf
          sudo chown -R www-data:www-data .
          sudo chmod -R 777 .
          pwd
          ls -l
          ls -a
          ls -a ./nginx/conf.d
          cat ./nginx/conf.d/laravel.conf
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
          php artisan key:generate
          php artisan config:cache

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          sleep 40
          docker-compose exec -T app php artisan migrate --force
          docker ps

      - name: Check file permissions
        run: docker-compose exec -T app ls -l /var/www

      - name: Check logs of app container
        run: docker logs laravel_app

      - name: Check logs of webserver container
        run: docker logs nginx

      - name: Run tests inside Docker container
        run: docker-compose exec -T app php artisan test
