name: Run PHPStan Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-phpstan-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install PHP Dependencies
        run: |
          composer install --no-interaction --no-plugins --no-scripts

      - name: Validate PHPStan Configuration
        run: vendor/bin/phpstan --version

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
